branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - prepareCmd: |
        # Update Chart.yaml version with the new release version
        sed -i "s/^version:.*/version: ${nextRelease.version}/" Chart.yaml
  - "@semantic-release/github"
preset: "conventionalcommits"
tagFormat: "v${version}"