branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - prepareCmd: |
        # Update Chart.yaml version with the new release version (remove 'v' prefix)
        version_without_v=$(echo "${nextRelease.version}" | sed 's/^v//')
        sed -i "s/^version:.*/version: $version_without_v/" Chart.yaml
  - "@semantic-release/github"
preset: "conventionalcommits"
tagFormat: "v${version}"