{{- if not (.Values.database).url }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  labels:
    app.kubernetes.io/component: database
type: Opaque
data:
  POSTGRES_USER: {{ "ctf" | b64enc | quote }}
  POSTGRES_PASSWORD: {{ "ctf" | b64enc | quote}}
  POSTGRES_DB: {{ "ctf" | b64enc | quote }}
{{- end }}