apiVersion: v1
kind: Secret
metadata:
  name: postgres
  labels:
    app.kubernetes.io/component: database
type: Opaque
data:
{{- if not (.Values.database).url }}
  POSTGRES_USER: {{ "ctf" | b64enc | quote }}
  POSTGRES_PASSWORD: {{ "ctf" | b64enc | quote}}
  POSTGRES_DB: {{ "ctf" | b64enc | quote }}
  DATABASE_URL: {{ "postgresql://ctf:ctf@postgres:5432/ctf" | b64enc | quote }}
{{- else }}
  DATABASE_URL: {{ .Values.database.url | b64enc | quote }}
{{- end }}